//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
  
    public partial class TF_BOM:ERPEntity
    { 

        //BOM_NO ITM PRD_NO PRD_MARK    ID_NO NAME    WH_NO BOM_ID  UNIT QTY QTY1
        public string LEVEL1 { get; set; }
        public string BOM_NO { get; set; }
        //public int ITM { get; set; }
        public string PRD_NO { get; set; }
        public string ChildPrdNo { get; set; }
        //public string PRD_MARK { get; set; }
        public string ID_NO { get; set; }
        public string NAME { get; set; }
        public string ChildName { get; set; }
        public string SPC { get; set; }
        public string ChildSPC { get; set; }
        public string SNM { get; set; }
        public string NAME_ENG { get; set; }
        //public string WH_NO { get; set; }
        public string QTY { get; set; }

        public List<TF_BOM> Children { get; set; } = new List<TF_BOM>();
        //BOM_NO,
        //PRD_NO,
        //NAME ,
        //SPC ,
        //LEVEL1 ,
       // A.PRD_NO ,
       // A.ID_NO,
       // A.NAME,
        //B.SNM ,
        //B.NAME_ENG,
        //B.SPC,
        //A.WH_NO ,
        //A.QTY








        //public string BOM_ID { get; set; }
        //public string WH_NO { get; set; }
        //public string UNIT { get; set; }
        //public decimal? QTY1 { get; set; }

        // LOS_RTO CST PRD_NO_UP   ID_NO_UP EXP_ID  PRD_NO_CHG REM START_DD END_DD  
        //public decimal? LOS_RTO { get; set; }
        //public decimal? CST { get; set; }
        //public string PRD_NO_UP { get; set; }
        //public string ID_NO_UP { get; set; }
        //public string EXP_ID { get; set; }
        //public string PRD_NO_CHG { get; set; }
        //public string REM { get; set; }
        //public DateTime? START_DD { get; set; }
        //public DateTime? END_DD { get; set; }
        //ZC_NO TW_ID   USEIN_NO QTY_BAS PZ_ID COMPOSE_IDNO    UP_STD UP_TAX  CUS_NO RTO_TAX EXC_RTO
        //public string ZC_NO { get; set; }
        //public string TW_ID { get; set; }
        //public string USEIN_NO { get; set; }
        //public decimal? QTY_BAS { get; set; }
        //public string PZ_ID { get; set; }
        //public string COMPOSE_IDNO { get; set; }
        //public decimal? UP_STD { get; set; }
        //public decimal? UP_TAX { get; set; }
        //public string CUS_NO { get; set; }
        //public decimal? RTO_TAX { get; set; }
        //public decimal? EXC_RTO { get; set; }
        //CUR_ID IS_SO_RES CHG_RTO PRE_ITM BL_RTO CUS_NO2 PRD_NO_OLD CL_RTO CST_ML
        //public string CUR_ID { get; set; }
        //public string IS_SO_RES { get; set; }
        //public string CHG_RTO { get; set; }
        //public string SNM { get; set; }
        //public string SPC { get; set; }
        // public int? PRE_ITM { get; set; }
        // public decimal? BL_RTO { get; set; }
        //public string CUS_NO2 { get; set; }
        //public string PRD_NO_OLD { get; set; }
        //public decimal? CL_RTO { get; set; }
        //public decimal? CST_ML { get; set; }

        //    CST_MAN CST_MAK CST_PRD CST_OUT RTO_PEI PEI_RTO CHG_DD QTY_LOST_FIX    QTY_BL_FIX

        //public decimal? CST_MAN { get; set; }
        //public decimal? CST_MAK { get; set; }
        //public decimal? CST_PRD { get; set; }
        //public decimal? CST_OUT { get; set; }
        //public decimal? RTO_PEI { get; set; }
        //public decimal? PEI_RTO { get; set; }
        //public DateTime? CHG_DD { get; set; }
        //public decimal? QTY_LOST_FIX { get; set; }
        //public decimal? QTY_BL_FIX { get; set; }
    }
}